### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ROODAY** [ROODAY/Swole-Patrol#1]
- [ ] Draw mockups of UI
- [ ] After mockups figure out what needs to be coded and redo this list
- [ ] Make clientside first on windows (must work on mobile as well, keep in mind that it scales well)
- [ ] Add in redis database and oauth on linux
